risky: false

version: 8.1

preset: recommended

tab-width: 4

use-tabs: false

enabled:
  - allman_braces

disabled:
  - symfony_braces

finder:
  name: "*.php"
  exclude:
    - "vendor"
    - "getid3"