risky: false

version: 8.1

preset: recommended

tab-width: 4

use-tabs: false

enabled:
  - allman_braces
  - long_array_syntax

disabled:
  - symfony_braces
  - short_array_syntax

finder:
  name: "*.php"
  exclude:
    - "vendor"
    - "getid3"